import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import NewsletterFooter from "@/components/Footer";
import 'aos/dist/aos.css';
import AuthProvider from "@/providers/AuthProvider";
import InitialLoaderWrapper from "@/components/InitialLoaderWrapper";
import Providers from "./providers";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EdCare Website",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <InitialLoaderWrapper duration={1000} fade={100} >
            <AuthProvider>
              <Header />
              <main className="max-w-7xl mx-auto py-2 px-4">
                {children}
              </main>
              <NewsletterFooter />
            </AuthProvider>
          </InitialLoaderWrapper>
        </body>
      </Providers>
    </html>
  );
}
